### ISSUE TITLE
Adapt patch size to available GPU memory

### ISSUE THREAD

**Issue by Abe404** [Abe404/RootPainter3D#2]
Network input (and corresponding output) patch size does not currently adapt to the available GPU memory.
It's possible for users to modify the patch size to suit their GPU memory requirements but it's annoying and error prone to do so.
Users shouldn't shouldn’t have to think about this. Patch size adaptation to available GPU memory should happen automatically

**Comment by Abe404** [comment]
Prototype code has been implemented for the server in the dev_mc branch that automatically detects a patch size that fits in the GPU (for a batch size of 4).

See relevant commit:
https://github.com/Abe404/RootPainter3D/commit/054cf149e03025014f1e1da1afd2899f0e1d5b5b

A problem with the current solution is that the patch size is also specified on the client:
https://github.com/Abe404/RootPainter3D/blob/master/painter/src/main/python/root_painter.py#L84


This is only used for the bounding box to detect (and compensate for) when a user selects an input region smaller than the minimum input size for the network.

I don't think there is a good reason for there to be a minimum input size for the network, so altering the network to handle input smaller than the default patch size would be my preferred solution. Another solution would be to somehow communicate the patch size from the server to client (I don't like this solution as it seems more complicated than necessary).








https://github.com/Abe404/RootPainter3D/blob/43d246a947ed271e39afe2dc4038dbcfb2ccb33a/painter/src/main/python/root_painter.py#L84

**Comment by orting** [comment]
Does not seem to fix the problem. Could be due to fragmentation in the memory reserved by torch as indicated by the error message below, where torch fails to allocate 2.30GiB with 23.65 GiB capacity, 20.27 GiB reserved, 16.35 GiB allocated and 2.21 GiB free. The numbers does not seems to add up, since nothing else is allocating on the GPU. Only seems to happen when starting training. I will play around with the memory tools to see if I can fix it.

CUDA out of memory. Tried to allocate 2.30 GiB (GPU 0; 23.65 GiB total capacity; 16.35 GiB already allocated; 2.21 GiB free; 20.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Abe404** [comment]
This makes sense as my patch size detector only uses inference to test memory allocation and training will use more memory due to stored gradients. I will update my patch size memory check to be a bit more involved later on today.

**Comment by orting** [comment]
Setting the environment variable `PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:100` solves the problem, but not clear what it implies for other allocations.
I think the better option is to make a more conservative estimate.

**Comment by Abe404** [comment]
OK I think I have a solution for this now :) and have updated the dev_mc branch

Most of the relevant changes are in:
https://github.com/Abe404/RootPainter3D/commit/c2a66b66ac89f0b4ab3339e0331b4e49b44b1ee7

Basically it tests some patch sizes that are known to work (compatible input/output shapes) and then decreases the size until it gets to one that doesn't return a memory error when training a network. Then it returns the next size smaller than the size it found just to be safe.

Please let me know how it goes with testing.

For your use case I expect this to work OK (hopefully) but there are still some potential problems to consider:

1. If a high memory GPU (or small images) is used then there is a risk that the patch could be bigger than the images. This isn't handled well yet.
2. A related problem is that the client currently has the patch size hard coded to ensure the images are sufficiently padded. I think adding some padding on the server for images that are too small is probably the easiest solution.

**Comment by Abe404** [comment]
It worked with my own tests and I haven't received any more complaints from the users so I will close this for now.
