### ISSUE TITLE
RootPainter max workers specifiable

### ISSUE THREAD

**Issue by jenspete** [Abe404/RootPainter3D#21]
RootPainter server eats up all the CPU resources, which may lead to problems running the server and client on the same machine. It also makes it hard to run other things in parallel.

**Comment by Abe404** [comment]
--maxworkers argument is now available.

Fixed in:

https://github.com/Abe404/RootPainter3D/commit/0f0203283639c738f009b0013b24dc7775475fbe
and
https://github.com/Abe404/RootPainter3D/commit/d342eeec57d59ae2953d5521e945f70475ab1383

Please let me know if you experience any problems with this.

**Comment by Abe404** [comment]
For an example (ran from inside trainer directory):

> python main.py --maxworkers 6
