### ISSUE TITLE
"Redo" and "Save annotation" both have Ctrl + Shift + Z as shortcut

### ISSUE THREAD

**Issue by orting** [Abe404/RootPainter3D#23]
"Redo" and "Save annotation" both have Ctrl + Shift + Z as shortcut.
Using the shortcut does nothing and gives the following output

    QAction::event: Ambiguous shortcut overload: Ctrl+Shift+Z

Maybe make "Save annotation" Ctrl + Shift + S?

**Comment by Abe404** [comment]
https://github.com/Abe404/RootPainter3D/commit/41fdb0e38868df2a7c66fa89df053ec9c47e3f3d
